# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f463381308454a7578ba47d2531c8039a6e28f24528b6bfbab21dc15a8650d9ce6c3cbb1a5ec58986ef31f7194f6952ee0b9c2c1f1b7de959b1c4b84de5e416

test:
  secret_key_base: d5b5877eaf490916684c612295426536b85186866ad440578ba59b8698908b527f58fc0599e4c18e2c39fcb7d8363ae7edc58290581a4e6a2bc3a9b34bbe7ba1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
